[package]
name = "kwm"
version = "0.1.0"
edition = "2021"

[dependencies]
wayland-server = "0.30.1"
smithay = { git = "https://github.com/Smithay/smithay", rev = "5f1674cc825881f88d9ad6d684cc4f58e344be40" }
anyhow = "1.0.75"
